### ISSUE TITLE
unable to install on linux system

### ISSUE THREAD

**Issue by kencyzhang** [pynetwork/pypcap#38] opened 2017-03-12 09:27 UTC
# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, Extension
ImportError: No module named setuptools

what's the matter? help

**Comment by hellais** [comment] 2017-03-22 12:58
What version of python are you using and on which platform?

You are probably running a fairly outdated version of python without setuptool. You should be able to install it by running:
```
pip install setuptools
```

Or get it from your package manager.

**Comment by hellais** [comment] 2017-11-21 09:24
I would say this is not a bug of the library, but an issues with the users platform. I am closing it for the moment, but if you still haven't managed to get it to work feel free to report back here 😃

**Closed by hellais** 2017-11-21 09:24 UTC
